### PR TITLE
Other boards

### PR DESCRIPTION
**Pull request by mitchellblom**
@webbdm for you to merge into what you're doing tonight.

### CODE REVIEW

**Comment by BSGreaves** [comment]
I think it's fine to merge. However, IMO the partial needs different logic. When they click on a user, it should change the url to something like boards/:uid, where it puts the other user's uid in the URL. Then we use a controller like PublicBoardList.Ctrl (for example) and re-use the board list partial. PublicBoardList.Ctrl should grab the uid from the URL, then make a FB call to get user's object (so we can get their username), then make a FB call to get the user's boards and display them. TLDR we need totally different logic for public users and boards.

**Comment by BSGreaves** [comment]
But we should go ahead and merge it now IMO, and update that stuff later, so that whoever is dependent on this base functionality can have it :)

**Comment by mitchellblom** [comment]
I can rewrite that tomorrow at lunch. Leave room for it.

**Comment by webbdm** [comment]
Sounds good to me.

Schmerge 👍

**Pull request merged**
